
CREATE TABLE IF NOT EXISTS kry (
  service_name VARCHAR(250) PRIMARY KEY,
  url VARCHAR(250) NOT NULL,
  active_ind VARCHAR (20),
  created_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);